p = lambda n, s: "{} in {}".format((((n + 24 * 60) // 60) % 24) * 100 + (n % 60), s)
n = int(input())
normal = (n // 100) * 60 + (n % 100)
print(p(normal, "Ottawa"))
print(p(normal - 180, "Victoria"))
print(p(normal - 120, "Edmonton"))
print(p(normal - 60, "Winnipeg"))
print(p(normal, "Toronto"))
print(p(normal + 60, "Halifax"))
print(p(normal + 90, "St. John's"))